In [1]:
import numpy as np
from gilbert2d import numpy_gilbert2d
from gilbert.gilbert3d import numpy_gilbert3d

In [2]:
size = 4
depth = 3
indexes = numpy_gilbert3d(size,size,depth)

X = np.arange(size*size*depth).reshape((size,size,depth))
k = X[indexes[:,0], indexes[:,1], indexes[:,2]]

print(X)
print(k)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]]]
[ 0  1 13 12 15 16  4  3  6  7 18 19 22 21  9 10 11 44 43 32 30 33 34 47
 46 45 39 40 28 27 24 25 37 36]


In [3]:
indexes_2d = numpy_gilbert2d(size,size)

X2D = np.arange(size*size).reshape((size,size))
k = X2D[indexes_2d[:,0], indexes_2d[:,1]]

print(X2D)
print(k)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 0  4  5  1  2  3  7  6 10 11 15 14 13  9  8 12]
